### ISSUE TITLE
Using Phel library/code in PHP

### ISSUE THREAD

**Issue by mabasic** [jenshaase/phel-lang#140]
Recently, I have been reading about Hy lang and one of the things that intrigued me very much is the ability to run Hy code from Python and opposite.

> The Hy compiler works by reading Hy source code into Hy model objects and compiling the Hy model objects into Python abstract syntax tree (ast) objects. Python AST objects can then be compiled and run by Python itself, byte-compiled for faster execution later, or rendered into Python source code. You can even mix Python and Hy code in the same project, or even the same file, which can be a good way to get your feet wet in Hy.

Currently, Phel can run PHP code, but not the other way around.

What is preventing Phel from being callable from PHP?

Disclaimer. I don't know how a programming language is built but I imagine that a Phel library/namespace/source file can be converted to a std class or something similar to provide phel public functions and variables as class methods and properties in php.

The benefit of something like this would be that Phel adoption and usability would be greater because we could add Phel code to existing PHP projects. 

Looking for feedback @jenshaase @Chemaclass 

I am willing to work on this if possible. Maybe a PHP package which would read/import Phel files as PHP classes or something similar.

**Comment by jenshaase** [comment]
Hi,

in general this is possible. Phel Code is compiled to valid PHP Code. If you compile a Phel file to a PHP file you can imported it using `require_once` for example. However, there are some drawbacks.

If you compile the following Phel File to PHP:
```
(ns test)

(def foo 1)

(defn bar [x] x)
```
it will look something like this:
```php
<?php

$GLOBALS["__phel"]["test"]["foo"] = 1;

$GLOBALS["__phel"]["test"]["bar"] = new class() extends \Phel\Lang\AFn {
  public function __invoke($x) {
    return $x;
  }
};
```

So in order to call the `bar` function in PHP land you have to do `$GLOBALS["__phel"]["test"]["bar"](10);`. It is not nice and probably people will not like it.

It best case the generated PHP file would look more like PHP:
```php
<?php
namespace test;

$x = 1;

function bar($x) {
  return $x;
}
```

But this is not possible because namespaces are only bound to classes and interfaces but not to functions or variables. If you would import the PHP file above in another PHP file you will call the `bar` function like this:

```php
<?php
namespace foobar;

require_once "path/to/generatedFile.php";

bar(1); // but not like \test\bar(1);
```

Regarding Hy (I'm not a expert in Hy or Python):

Hy is probably build for the case that it can be used from Python. As far as I can see it is more like an alternative syntax than it's own language. The Python language has also the features to make it easier. For example it has a module system where you can hook into and preprocess loaded modules. Something like that is not possible in PHP.

Therefore, I will not support such a feature. If you want to do it you can do it, but you are responsible for it ;)

**Comment by mabasic** [comment]
@jenshaase Thank you for explaining. 

I got a few ideas from your answer to research.

**Comment by mabasic** [comment]
I've seen in Laravel that they use single action controllers which are basically classes with a single `__invoke` method.

If we could get from this:

```
<?php
namespace test;

$x = 1;

function bar($x) {
  return $x;
}
```

to this:

```
<?php
namespace test;

class bar
{
    public function __invoke($x)
    {
        return $x;
    }
}
```



Then we could call Phel functions like so from PHP:

```
$bar = new \test\bar();

echo $bar("test");
```

@jenshaase What do you think?

I'm still thinking how to solve namespaced variables. Maybe an agreed upon generic class name to hold all public Phel variables.

**Comment by jenshaase** [comment]
I though about that too. However, it caused other problem I didn't remember yet.

I also don't like the solutions using `$GLOBALS`. But it was the the only way I found to solve all my problems.

**Comment by mabasic** [comment]
How about a PHP package which will wrap around `$GLOBALS["__phel"]["test"]["bar"](10);` somehow?

**Comment by jenshaase** [comment]
If have a few ideas on how to do it. Since, I haven't see myself a use case to use Phel from PHP, what is your use case?

**Comment by aszenz** [comment]
My own use case is to gradually introduce the language in a large scale application, with one way inter op I can easily reuse the existing functionality built into the application but any new functionality I add is only accessible from within phel which is slightly limiting.

What is even more limiting though is that phel packages will not be accessible to php code so that affects the development of libraries built in phel because they will only be targeting a very narrow audience instead of the whole php ecosystem.

I think many library authors would be willing write packages for php in a better language like phel just for their developer experience.

One more point I would like to mention is that two way inter op makes more sense if the language is meant to co-exist alongside php, but if you are thinking of having additional compilation target's later for phel (like javascript) then this option is less desired.

**Comment by jenshaase** [comment]
Thanks for that. I will investigate more in this topic. 
I created another issue for that #209
